BaseUrl= "http://top178.gitee.io/ys/"
LanguageCode= "fr-FR"
Title= "健康瘦身官微"
paginate = 5
DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2019"
canonifyurls = true
publishDir = "docs"
theme="casper"

[params]
  description = "千万条路，瘦身，从来都是一个人"
  metadescription = "metades"
  cover = "./images/cover_p1.png"
  author = "Science"
  authorlocation = "china"
  authorwebsite = "http://vjeantet.fr"
  authorbio= "my bio"

  # googleAnalyticsUserID = "UA-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..."
 
 
  hideHUGOSupport = true
  
  # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
  # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
  # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
  hjsStyle = "default"

[params.social]
    twitter = "your_twitter"


[[menu.main]]
  name = "文章"
  weight = -1
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "关于"
  weight = -2
  identifier = "about"
  url = "/about"